/*
 * Auto-generated by RDF4JSchemaGenerator
 */
package com.axiell.arena.rdf.model.vocabulary;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;

/**
 * "CIDOC Conceptual Reference Model"@en
 * Implementation of the CIDOC Conceptual Reference Model, version 5.0.1, in OWL 2.
 *
 * Namespace CIDOC
 * Prefix: {@code <http://purl.org/NET/cidoc-crm/core>}
 *
 * @see <a href="http://bloody-byte.net/rdf/cidoc-crm/index.html">http://bloody-byte.net/rdf/cidoc-crm/index.html</a>
 */
public class CIDOC {

	/**
	 * {@code <http://purl.org/NET/cidoc-crm/core>}
	 */
	public static final String NAMESPACE = "http://purl.org/NET/cidoc-crm/core"; 

	/**
	 * {@code <http://purl.org/NET/cidoc-crm/core>}
	 */
	public static final IRI NAMESPACE_IRI;

	/**
	 * {@code <CIDOC>}
	 */
	public static final String PREFIX = "CIDOC"; 

	/**********************
	 * IRI String Constants
	 **********************/

	/*****************************
	 * Local Name String Constants
	 *****************************/

	/***************
	 * IRI Constants
	 ***************/

	/**
	 * Transfer of Custody
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E10_Transfer_of_Custody}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E10_Transfer_of_Custody">#E10_Transfer_of_Custody</a>
	 */
	public static final IRI E10_Transfer_of_Custody;

	/**
	 * Modification
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E11_Modification}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E11_Modification">#E11_Modification</a>
	 */
	public static final IRI E11_Modification;

	/**
	 * Production
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E12_Production}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E12_Production">#E12_Production</a>
	 */
	public static final IRI E12_Production;

	/**
	 * Attribute Assignment
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E13_Attribute_Assignment}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E13_Attribute_Assignment">#E13_Attribute_Assignment</a>
	 */
	public static final IRI E13_Attribute_Assignment;

	/**
	 * Condition Assignment
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E14_Condition_Assessment}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E14_Condition_Assessment">#E14_Condition_Assessment</a>
	 */
	public static final IRI E14_Condition_Assessment;

	/**
	 * Identifier Assignment
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E15_Identifier_Assignment}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E15_Identifier_Assignment">#E15_Identifier_Assignment</a>
	 */
	public static final IRI E15_Identifier_Assignment;

	/**
	 * Measurement
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E16_Measurement}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E16_Measurement">#E16_Measurement</a>
	 */
	public static final IRI E16_Measurement;

	/**
	 * Type Assignment
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E17_Type_Assignment}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E17_Type_Assignment">#E17_Type_Assignment</a>
	 */
	public static final IRI E17_Type_Assignment;

	/**
	 * Physical Thing
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E18_Physical_Thing}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E18_Physical_Thing">#E18_Physical_Thing</a>
	 */
	public static final IRI E18_Physical_Thing;

	/**
	 * Physical Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E19_Physical_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E19_Physical_Object">#E19_Physical_Object</a>
	 */
	public static final IRI E19_Physical_Object;

	/**
	 * CRM Entity
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E1_CRM_Entity}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E1_CRM_Entity">#E1_CRM_Entity</a>
	 */
	public static final IRI E1_CRM_Entity;

	/**
	 * Biological Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E20_Biological_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E20_Biological_Object">#E20_Biological_Object</a>
	 */
	public static final IRI E20_Biological_Object;

	/**
	 * Person
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E21_Person}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E21_Person">#E21_Person</a>
	 */
	public static final IRI E21_Person;

	/**
	 * Man-Made Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E22_Man-Made_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E22_Man-Made_Object">#E22_Man-Made_Object</a>
	 */
	public static final IRI E22_Man_Made_Object;

	/**
	 * Physical Man-Made Thing
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E24_Physical_Man-Made_Thing}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E24_Physical_Man-Made_Thing">#E24_Physical_Man-Made_Thing</a>
	 */
	public static final IRI E24_Physical_Man_Made_Thing;

	/**
	 * Man-Made Feature
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E25_Man-Made_Feature}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E25_Man-Made_Feature">#E25_Man-Made_Feature</a>
	 */
	public static final IRI E25_Man_Made_Feature;

	/**
	 * Physical Feature
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E26_Physical_Feature}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E26_Physical_Feature">#E26_Physical_Feature</a>
	 */
	public static final IRI E26_Physical_Feature;

	/**
	 * Site
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E27_Site}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E27_Site">#E27_Site</a>
	 */
	public static final IRI E27_Site;

	/**
	 * Conceptual_Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E28_Conceptual_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E28_Conceptual_Object">#E28_Conceptual_Object</a>
	 */
	public static final IRI E28_Conceptual_Object;

	/**
	 * Design or Procedure
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E29_Design_or_Procedure}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E29_Design_or_Procedure">#E29_Design_or_Procedure</a>
	 */
	public static final IRI E29_Design_or_Procedure;

	/**
	 * Temporal Entity
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E2_Temporal_Entity}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E2_Temporal_Entity">#E2_Temporal_Entity</a>
	 */
	public static final IRI E2_Temporal_Entity;

	/**
	 * Right
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E30_Right}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E30_Right">#E30_Right</a>
	 */
	public static final IRI E30_Right;

	/**
	 * Document
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E31_Document}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E31_Document">#E31_Document</a>
	 */
	public static final IRI E31_Document;

	/**
	 * Authority Document
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E32_Authority_Document}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E32_Authority_Document">#E32_Authority_Document</a>
	 */
	public static final IRI E32_Authority_Document;

	/**
	 * Linguistic Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E33_Linguistic_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E33_Linguistic_Object">#E33_Linguistic_Object</a>
	 */
	public static final IRI E33_Linguistic_Object;

	/**
	 * Inscription
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E34_Inscription}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E34_Inscription">#E34_Inscription</a>
	 */
	public static final IRI E34_Inscription;

	/**
	 * Title
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E35_Title}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E35_Title">#E35_Title</a>
	 */
	public static final IRI E35_Title;

	/**
	 * Visual Item
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E36_Visual_Item}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E36_Visual_Item">#E36_Visual_Item</a>
	 */
	public static final IRI E36_Visual_Item;

	/**
	 * Mark
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E37_Mark}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E37_Mark">#E37_Mark</a>
	 */
	public static final IRI E37_Mark;

	/**
	 * Image
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E38_Image}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E38_Image">#E38_Image</a>
	 */
	public static final IRI E38_Image;

	/**
	 * Actor
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E39_Actor}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E39_Actor">#E39_Actor</a>
	 */
	public static final IRI E39_Actor;

	/**
	 * Condition State
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E3_Condition_State}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E3_Condition_State">#E3_Condition_State</a>
	 */
	public static final IRI E3_Condition_State;

	/**
	 * Legal Body
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E40_Legal_Body}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E40_Legal_Body">#E40_Legal_Body</a>
	 */
	public static final IRI E40_Legal_Body;

	/**
	 * Appellation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E41_Appellation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E41_Appellation">#E41_Appellation</a>
	 */
	public static final IRI E41_Appellation;

	/**
	 * Identifier
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E42_Identifier}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E42_Identifier">#E42_Identifier</a>
	 */
	public static final IRI E42_Identifier;

	/**
	 * Place Appellation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E44_Place_Appellation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E44_Place_Appellation">#E44_Place_Appellation</a>
	 */
	public static final IRI E44_Place_Appellation;

	/**
	 * Address
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E45_Address}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E45_Address">#E45_Address</a>
	 */
	public static final IRI E45_Address;

	/**
	 * Section Definition
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E46_Section_Definition}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E46_Section_Definition">#E46_Section_Definition</a>
	 */
	public static final IRI E46_Section_Definition;

	/**
	 * Spatial Coordinates
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E47_Spatial_Coordinates}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E47_Spatial_Coordinates">#E47_Spatial_Coordinates</a>
	 */
	public static final IRI E47_Spatial_Coordinates;

	/**
	 * Time Appellation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E49_Time_Appellation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E49_Time_Appellation">#E49_Time_Appellation</a>
	 */
	public static final IRI E49_Time_Appellation;

	/**
	 * Period
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E4_Period}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E4_Period">#E4_Period</a>
	 */
	public static final IRI E4_Period;

	/**
	 * Date
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E50_Date}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E50_Date">#E50_Date</a>
	 */
	public static final IRI E50_Date;

	/**
	 * Contact Point
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E51_Contact_Point}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E51_Contact_Point">#E51_Contact_Point</a>
	 */
	public static final IRI E51_Contact_Point;

	/**
	 * Time-Span
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E52_Time-Span}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E52_Time-Span">#E52_Time-Span</a>
	 */
	public static final IRI E52_Time_Span;

	/**
	 * Place
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E53_Place}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E53_Place">#E53_Place</a>
	 */
	public static final IRI E53_Place;

	/**
	 * Dimension
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E54_Dimension}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E54_Dimension">#E54_Dimension</a>
	 */
	public static final IRI E54_Dimension;

	/**
	 * Type
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E55_Type}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E55_Type">#E55_Type</a>
	 */
	public static final IRI E55_Type;

	/**
	 * Language
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E56_Language}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E56_Language">#E56_Language</a>
	 */
	public static final IRI E56_Language;

	/**
	 * Material
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E57_Material}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E57_Material">#E57_Material</a>
	 */
	public static final IRI E57_Material;

	/**
	 * Measurement Unit
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E58_Measurement_Unit}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E58_Measurement_Unit">#E58_Measurement_Unit</a>
	 */
	public static final IRI E58_Measurement_Unit;

	/**
	 * Event
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E5_Event}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E5_Event">#E5_Event</a>
	 */
	public static final IRI E5_Event;

	/**
	 * Beginning of Existence
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E63_Beginning_of_Existence}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E63_Beginning_of_Existence">#E63_Beginning_of_Existence</a>
	 */
	public static final IRI E63_Beginning_of_Existence;

	/**
	 * End of Existence
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E64_End_of_Existence}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E64_End_of_Existence">#E64_End_of_Existence</a>
	 */
	public static final IRI E64_End_of_Existence;

	/**
	 * Creation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E65_Creation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E65_Creation">#E65_Creation</a>
	 */
	public static final IRI E65_Creation;

	/**
	 * Formation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E66_Formation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E66_Formation">#E66_Formation</a>
	 */
	public static final IRI E66_Formation;

	/**
	 * Birth
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E67_Birth}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E67_Birth">#E67_Birth</a>
	 */
	public static final IRI E67_Birth;

	/**
	 * Dissolution
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E68_Dissolution}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E68_Dissolution">#E68_Dissolution</a>
	 */
	public static final IRI E68_Dissolution;

	/**
	 * Death
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E69_Death}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E69_Death">#E69_Death</a>
	 */
	public static final IRI E69_Death;

	/**
	 * Destruction
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E6_Destruction}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E6_Destruction">#E6_Destruction</a>
	 */
	public static final IRI E6_Destruction;

	/**
	 * Thing
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E70_Thing}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E70_Thing">#E70_Thing</a>
	 */
	public static final IRI E70_Thing;

	/**
	 * Man-Made Thing
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E71_Man-Made_Thing}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E71_Man-Made_Thing">#E71_Man-Made_Thing</a>
	 */
	public static final IRI E71_Man_Made_Thing;

	/**
	 * Legal Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E72_Legal_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E72_Legal_Object">#E72_Legal_Object</a>
	 */
	public static final IRI E72_Legal_Object;

	/**
	 * Information Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E73_Information_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E73_Information_Object">#E73_Information_Object</a>
	 */
	public static final IRI E73_Information_Object;

	/**
	 * Group
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E74_Group}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E74_Group">#E74_Group</a>
	 */
	public static final IRI E74_Group;

	/**
	 * Conceptual Object Appellation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E75_Conceptual_Object_Appellation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E75_Conceptual_Object_Appellation">#E75_Conceptual_Object_Appellation</a>
	 */
	public static final IRI E75_Conceptual_Object_Appellation;

	/**
	 * Persistent Item
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E77_Persistent_Item}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E77_Persistent_Item">#E77_Persistent_Item</a>
	 */
	public static final IRI E77_Persistent_Item;

	/**
	 * Collection
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E78_Collection}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E78_Collection">#E78_Collection</a>
	 */
	public static final IRI E78_Collection;

	/**
	 * Part Addition
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E79_Part_Addition}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E79_Part_Addition">#E79_Part_Addition</a>
	 */
	public static final IRI E79_Part_Addition;

	/**
	 * Activity
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E7_Activity}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E7_Activity">#E7_Activity</a>
	 */
	public static final IRI E7_Activity;

	/**
	 * Part Removal
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E80_Part_Removal}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E80_Part_Removal">#E80_Part_Removal</a>
	 */
	public static final IRI E80_Part_Removal;

	/**
	 * Transformation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E81_Transformation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E81_Transformation">#E81_Transformation</a>
	 */
	public static final IRI E81_Transformation;

	/**
	 * Actor Appellation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E82_Actor_Appellation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E82_Actor_Appellation">#E82_Actor_Appellation</a>
	 */
	public static final IRI E82_Actor_Appellation;

	/**
	 * Type Creation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E83_Type_Creation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E83_Type_Creation">#E83_Type_Creation</a>
	 */
	public static final IRI E83_Type_Creation;

	/**
	 * Information Carrier
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E84_Information_Carrier}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E84_Information_Carrier">#E84_Information_Carrier</a>
	 */
	public static final IRI E84_Information_Carrier;

	/**
	 * Joining
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E85_Joining}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E85_Joining">#E85_Joining</a>
	 */
	public static final IRI E85_Joining;

	/**
	 * Leaving
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E86_Leaving}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E86_Leaving">#E86_Leaving</a>
	 */
	public static final IRI E86_Leaving;

	/**
	 * Curation Activity
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E87_Curation_Activity}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E87_Curation_Activity">#E87_Curation_Activity</a>
	 */
	public static final IRI E87_Curation_Activity;

	/**
	 * Propositional Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E89_Propositional_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E89_Propositional_Object">#E89_Propositional_Object</a>
	 */
	public static final IRI E89_Propositional_Object;

	/**
	 * Acquisition
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E8_Acquisition}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E8_Acquisition">#E8_Acquisition</a>
	 */
	public static final IRI E8_Acquisition;

	/**
	 * Symbolic Object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E90_Symbolic_Object}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E90_Symbolic_Object">#E90_Symbolic_Object</a>
	 */
	public static final IRI E90_Symbolic_Object;

	/**
	 * Move
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#E9_Move}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#E9_Move">#E9_Move</a>
	 */
	public static final IRI E9_Move;

	/**
	 * {@code http://purl.org/NET/cidoc-crm/core#EntityNotation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#EntityNotation">#EntityNotation</a>
	 */
	public static final IRI EntityNotation;

	/**
	 * was death of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P100_was_death_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P100_was_death_of">#P100_was_death_of</a>
	 */
	public static final IRI P100_was_death_of;

	/**
	 * had as general use
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P101_had_as_general_use}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P101_had_as_general_use">#P101_had_as_general_use</a>
	 */
	public static final IRI P101_had_as_general_use;

	/**
	 * has title
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P102_has_title}
	 * <p>
	 * Properties: P102.1 has type: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P102_has_title">#P102_has_title</a>
	 */
	public static final IRI P102_has_title;

	/**
	 * was intended for
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P103_was_intended_for}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P103_was_intended_for">#P103_was_intended_for</a>
	 */
	public static final IRI P103_was_intended_for;

	/**
	 * is subject to
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P104_is_subject_to}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P104_is_subject_to">#P104_is_subject_to</a>
	 */
	public static final IRI P104_is_subject_to;

	/**
	 * right held by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P105_right_held_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P105_right_held_by">#P105_right_held_by</a>
	 */
	public static final IRI P105_right_held_by;

	/**
	 * is composed of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P106_is_composed_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P106_is_composed_of">#P106_is_composed_of</a>
	 */
	public static final IRI P106_is_composed_of;

	/**
	 * has current or former member
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P107_has_current_or_former_member}
	 * <p>
	 * Properties: P107.1 kind of member: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P107_has_current_or_former_member">#P107_has_current_or_former_member</a>
	 */
	public static final IRI P107_has_current_or_former_member;

	/**
	 * has produced
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P108_has_produced}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P108_has_produced">#P108_has_produced</a>
	 */
	public static final IRI P108_has_produced;

	/**
	 * has current or former curator
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P109_has_current_or_former_curator}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P109_has_current_or_former_curator">#P109_has_current_or_former_curator</a>
	 */
	public static final IRI P109_has_current_or_former_curator;

	/**
	 * falls within
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P10_falls_within}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P10_falls_within">#P10_falls_within</a>
	 */
	public static final IRI P10_falls_within;

	/**
	 * augmented
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P110_augmented}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P110_augmented">#P110_augmented</a>
	 */
	public static final IRI P110_augmented;

	/**
	 * added
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P111_added}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P111_added">#P111_added</a>
	 */
	public static final IRI P111_added;

	/**
	 * diminished
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P112_diminished}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P112_diminished">#P112_diminished</a>
	 */
	public static final IRI P112_diminished;

	/**
	 * removed
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P113_removed}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P113_removed">#P113_removed</a>
	 */
	public static final IRI P113_removed;

	/**
	 * is equal in time to
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P114_is_equal_in_time_to}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P114_is_equal_in_time_to">#P114_is_equal_in_time_to</a>
	 */
	public static final IRI P114_is_equal_in_time_to;

	/**
	 * finishes
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P115_finishes}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P115_finishes">#P115_finishes</a>
	 */
	public static final IRI P115_finishes;

	/**
	 * starts
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P116_starts}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P116_starts">#P116_starts</a>
	 */
	public static final IRI P116_starts;

	/**
	 * occurs during
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P117_occurs_during}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P117_occurs_during">#P117_occurs_during</a>
	 */
	public static final IRI P117_occurs_during;

	/**
	 * overlaps in time with
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P118_overlaps_in_time_with}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P118_overlaps_in_time_with">#P118_overlaps_in_time_with</a>
	 */
	public static final IRI P118_overlaps_in_time_with;

	/**
	 * meets in time with
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P119_meets_in_time_with}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P119_meets_in_time_with">#P119_meets_in_time_with</a>
	 */
	public static final IRI P119_meets_in_time_with;

	/**
	 * had participant
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P11_had_participant}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P11_had_participant">#P11_had_participant</a>
	 */
	public static final IRI P11_had_participant;

	/**
	 * occurs before
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P120_occurs_before}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P120_occurs_before">#P120_occurs_before</a>
	 */
	public static final IRI P120_occurs_before;

	/**
	 * overlaps with
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P121_overlaps_with}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P121_overlaps_with">#P121_overlaps_with</a>
	 */
	public static final IRI P121_overlaps_with;

	/**
	 * borders with
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P122_borders_with}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P122_borders_with">#P122_borders_with</a>
	 */
	public static final IRI P122_borders_with;

	/**
	 * resulted in
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P123_resulted_in}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P123_resulted_in">#P123_resulted_in</a>
	 */
	public static final IRI P123_resulted_in;

	/**
	 * transformed
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P124_transformed}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P124_transformed">#P124_transformed</a>
	 */
	public static final IRI P124_transformed;

	/**
	 * used object of type
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P125_used_object_of_type}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P125_used_object_of_type">#P125_used_object_of_type</a>
	 */
	public static final IRI P125_used_object_of_type;

	/**
	 * employed
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P126_employed}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P126_employed">#P126_employed</a>
	 */
	public static final IRI P126_employed;

	/**
	 * has broader term
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P127_has_broader_term}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P127_has_broader_term">#P127_has_broader_term</a>
	 */
	public static final IRI P127_has_broader_term;

	/**
	 * carries
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P128_carries}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P128_carries">#P128_carries</a>
	 */
	public static final IRI P128_carries;

	/**
	 * is about
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P129_is_about}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P129_is_about">#P129_is_about</a>
	 */
	public static final IRI P129_is_about;

	/**
	 * occurred in the presence of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P12_occurred_in_the_presence_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P12_occurred_in_the_presence_of">#P12_occurred_in_the_presence_of</a>
	 */
	public static final IRI P12_occurred_in_the_presence_of;

	/**
	 * shows features of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P130_shows_features_of}
	 * <p>
	 * Properties: P130.1 kind of similarity: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P130_shows_features_of">#P130_shows_features_of</a>
	 */
	public static final IRI P130_shows_features_of;

	/**
	 * is identified by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P131_is_identified_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P131_is_identified_by">#P131_is_identified_by</a>
	 */
	public static final IRI P131_is_identified_by;

	/**
	 * overlaps with
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P132_overlaps_with}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P132_overlaps_with">#P132_overlaps_with</a>
	 */
	public static final IRI P132_overlaps_with;

	/**
	 * is separated from
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P133_is_separated_from}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P133_is_separated_from">#P133_is_separated_from</a>
	 */
	public static final IRI P133_is_separated_from;

	/**
	 * continued
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P134_continued}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P134_continued">#P134_continued</a>
	 */
	public static final IRI P134_continued;

	/**
	 * created type
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P135_created_type}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P135_created_type">#P135_created_type</a>
	 */
	public static final IRI P135_created_type;

	/**
	 * was based on
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P136_was_based_on}
	 * <p>
	 * Properties: P136.1 in the taxonomic role: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P136_was_based_on">#P136_was_based_on</a>
	 */
	public static final IRI P136_was_based_on;

	/**
	 * exemplifies
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P137_exemplifies}
	 * <p>
	 * Properties: P137.1 in the taxonomic role: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P137_exemplifies">#P137_exemplifies</a>
	 */
	public static final IRI P137_exemplifies;

	/**
	 * represents
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P138_represents}
	 * <p>
	 * Properties: P138.1 mode of representation: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P138_represents">#P138_represents</a>
	 */
	public static final IRI P138_represents;

	/**
	 * has alternative form
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P139_has_alternative_form}
	 * <p>
	 * Properties: P139.1 has type: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P139_has_alternative_form">#P139_has_alternative_form</a>
	 */
	public static final IRI P139_has_alternative_form;

	/**
	 * destroyed
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P13_destroyed}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P13_destroyed">#P13_destroyed</a>
	 */
	public static final IRI P13_destroyed;

	/**
	 * assigned attribute to
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P140_assigned_attribute_to}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P140_assigned_attribute_to">#P140_assigned_attribute_to</a>
	 */
	public static final IRI P140_assigned_attribute_to;

	/**
	 * assigned
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P141_assigned}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P141_assigned">#P141_assigned</a>
	 */
	public static final IRI P141_assigned;

	/**
	 * used constituent
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P142_used_constituent}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P142_used_constituent">#P142_used_constituent</a>
	 */
	public static final IRI P142_used_constituent;

	/**
	 * joined
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P143_joined}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P143_joined">#P143_joined</a>
	 */
	public static final IRI P143_joined;

	/**
	 * joined with
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P144_joined_with}
	 * <p>
	 * Properties: P144.1 kind of member: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P144_joined_with">#P144_joined_with</a>
	 */
	public static final IRI P144_joined_with;

	/**
	 * separated
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P145_separated}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P145_separated">#P145_separated</a>
	 */
	public static final IRI P145_separated;

	/**
	 * separated from
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P146_separated_from}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P146_separated_from">#P146_separated_from</a>
	 */
	public static final IRI P146_separated_from;

	/**
	 * curated
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P147_curated}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P147_curated">#P147_curated</a>
	 */
	public static final IRI P147_curated;

	/**
	 * has component
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P148_has_component}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P148_has_component">#P148_has_component</a>
	 */
	public static final IRI P148_has_component;

	/**
	 * carried out by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P14_carried_out_by}
	 * <p>
	 * Properties: P14.1 in the role of: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P14_carried_out_by">#P14_carried_out_by</a>
	 */
	public static final IRI P14_carried_out_by;

	/**
	 * was influenced by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P15_was_influenced_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P15_was_influenced_by">#P15_was_influenced_by</a>
	 */
	public static final IRI P15_was_influenced_by;

	/**
	 * used specific object
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P16_used_specific_object}
	 * <p>
	 * Properties: P16.1 mode of use: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P16_used_specific_object">#P16_used_specific_object</a>
	 */
	public static final IRI P16_used_specific_object;

	/**
	 * was motivated by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P17_was_motivated_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P17_was_motivated_by">#P17_was_motivated_by</a>
	 */
	public static final IRI P17_was_motivated_by;

	/**
	 * was intended use of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P19_was_intended_use_of}
	 * <p>
	 * Properties: P19.1 mode of use: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P19_was_intended_use_of">#P19_was_intended_use_of</a>
	 */
	public static final IRI P19_was_intended_use_of;

	/**
	 * is identified by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P1_is_identified_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P1_is_identified_by">#P1_is_identified_by</a>
	 */
	public static final IRI P1_is_identified_by;

	/**
	 * had specific purpose
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P20_had_specific_purpose}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P20_had_specific_purpose">#P20_had_specific_purpose</a>
	 */
	public static final IRI P20_had_specific_purpose;

	/**
	 * had general purpose
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P21_had_general_purpose}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P21_had_general_purpose">#P21_had_general_purpose</a>
	 */
	public static final IRI P21_had_general_purpose;

	/**
	 * transferred title to
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P22_transferred_title_to}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P22_transferred_title_to">#P22_transferred_title_to</a>
	 */
	public static final IRI P22_transferred_title_to;

	/**
	 * transferred title from
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P23_transferred_title_from}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P23_transferred_title_from">#P23_transferred_title_from</a>
	 */
	public static final IRI P23_transferred_title_from;

	/**
	 * transferred title of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P24_transferred_title_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P24_transferred_title_of">#P24_transferred_title_of</a>
	 */
	public static final IRI P24_transferred_title_of;

	/**
	 * moved
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P25_moved}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P25_moved">#P25_moved</a>
	 */
	public static final IRI P25_moved;

	/**
	 * moved to
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P26_moved_to}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P26_moved_to">#P26_moved_to</a>
	 */
	public static final IRI P26_moved_to;

	/**
	 * moved from
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P27_moved_from}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P27_moved_from">#P27_moved_from</a>
	 */
	public static final IRI P27_moved_from;

	/**
	 * custody surrendered by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P28_custody_surrendered_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P28_custody_surrendered_by">#P28_custody_surrendered_by</a>
	 */
	public static final IRI P28_custody_surrendered_by;

	/**
	 * custody received by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P29_custody_received_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P29_custody_received_by">#P29_custody_received_by</a>
	 */
	public static final IRI P29_custody_received_by;

	/**
	 * has type
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P2_has_type}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P2_has_type">#P2_has_type</a>
	 */
	public static final IRI P2_has_type;

	/**
	 * transferred custody of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P30_transferred_custody_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P30_transferred_custody_of">#P30_transferred_custody_of</a>
	 */
	public static final IRI P30_transferred_custody_of;

	/**
	 * has modified
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P31_has_modified}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P31_has_modified">#P31_has_modified</a>
	 */
	public static final IRI P31_has_modified;

	/**
	 * used general technique
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P32_used_general_technique}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P32_used_general_technique">#P32_used_general_technique</a>
	 */
	public static final IRI P32_used_general_technique;

	/**
	 * used specific technique
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P33_used_specific_technique}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P33_used_specific_technique">#P33_used_specific_technique</a>
	 */
	public static final IRI P33_used_specific_technique;

	/**
	 * concerned
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P34_concerned}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P34_concerned">#P34_concerned</a>
	 */
	public static final IRI P34_concerned;

	/**
	 * has identified
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P35_has_identified}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P35_has_identified">#P35_has_identified</a>
	 */
	public static final IRI P35_has_identified;

	/**
	 * assigned
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P37_assigned}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P37_assigned">#P37_assigned</a>
	 */
	public static final IRI P37_assigned;

	/**
	 * deassigned
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P38_deassigned}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P38_deassigned">#P38_deassigned</a>
	 */
	public static final IRI P38_deassigned;

	/**
	 * measured
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P39_measured}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P39_measured">#P39_measured</a>
	 */
	public static final IRI P39_measured;

	/**
	 * has note
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P3_has_note}
	 * <p>
	 * Properties: P3.1 has type: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P3_has_note">#P3_has_note</a>
	 */
	public static final IRI P3_has_note;

	/**
	 * observed dimension
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P40_observed_dimension}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P40_observed_dimension">#P40_observed_dimension</a>
	 */
	public static final IRI P40_observed_dimension;

	/**
	 * classified
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P41_classified}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P41_classified">#P41_classified</a>
	 */
	public static final IRI P41_classified;

	/**
	 * assigned
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P42_assigned}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P42_assigned">#P42_assigned</a>
	 */
	public static final IRI P42_assigned;

	/**
	 * has dimension
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P43_has_dimension}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P43_has_dimension">#P43_has_dimension</a>
	 */
	public static final IRI P43_has_dimension;

	/**
	 * has condition
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P44_has_condition}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P44_has_condition">#P44_has_condition</a>
	 */
	public static final IRI P44_has_condition;

	/**
	 * consists of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P45_consists_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P45_consists_of">#P45_consists_of</a>
	 */
	public static final IRI P45_consists_of;

	/**
	 * is composed of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P46_is_composed_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P46_is_composed_of">#P46_is_composed_of</a>
	 */
	public static final IRI P46_is_composed_of;

	/**
	 * has preferred identifier
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P48_has_preferred_identifier}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P48_has_preferred_identifier">#P48_has_preferred_identifier</a>
	 */
	public static final IRI P48_has_preferred_identifier;

	/**
	 * has former or current keeper
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P49_has_former_or_current_keeper}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P49_has_former_or_current_keeper">#P49_has_former_or_current_keeper</a>
	 */
	public static final IRI P49_has_former_or_current_keeper;

	/**
	 * has time-span
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P4_has_time-span}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P4_has_time-span">#P4_has_time-span</a>
	 */
	public static final IRI P4_has_time_span;

	/**
	 * has current keeper
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P50_has_current_keeper}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P50_has_current_keeper">#P50_has_current_keeper</a>
	 */
	public static final IRI P50_has_current_keeper;

	/**
	 * has former or current owner
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P51_has_former_or_current_owner}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P51_has_former_or_current_owner">#P51_has_former_or_current_owner</a>
	 */
	public static final IRI P51_has_former_or_current_owner;

	/**
	 * has current owner
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P52_has_current_owner}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P52_has_current_owner">#P52_has_current_owner</a>
	 */
	public static final IRI P52_has_current_owner;

	/**
	 * has former or current location
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P53_has_former_or_current_location}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P53_has_former_or_current_location">#P53_has_former_or_current_location</a>
	 */
	public static final IRI P53_has_former_or_current_location;

	/**
	 * has current permanent location
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P54_has_current_permanent_location}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P54_has_current_permanent_location">#P54_has_current_permanent_location</a>
	 */
	public static final IRI P54_has_current_permanent_location;

	/**
	 * has current location
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P55_has_current_location}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P55_has_current_location">#P55_has_current_location</a>
	 */
	public static final IRI P55_has_current_location;

	/**
	 * bears feature
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P56_bears_feature}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P56_bears_feature">#P56_bears_feature</a>
	 */
	public static final IRI P56_bears_feature;

	/**
	 * has number of parts
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P57_has_number_of_parts}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P57_has_number_of_parts">#P57_has_number_of_parts</a>
	 */
	public static final IRI P57_has_number_of_parts;

	/**
	 * has section definition
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P58_has_section_definition}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P58_has_section_definition">#P58_has_section_definition</a>
	 */
	public static final IRI P58_has_section_definition;

	/**
	 * has section
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P59_has_section}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P59_has_section">#P59_has_section</a>
	 */
	public static final IRI P59_has_section;

	/**
	 * consists of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P5_consists_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P5_consists_of">#P5_consists_of</a>
	 */
	public static final IRI P5_consists_of;

	/**
	 * depicts
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P62_depicts}
	 * <p>
	 * Properties: P62.1 mode of depiction: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P62_depicts">#P62_depicts</a>
	 */
	public static final IRI P62_depicts;

	/**
	 * shows visual item
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P65_shows_visual_item}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P65_shows_visual_item">#P65_shows_visual_item</a>
	 */
	public static final IRI P65_shows_visual_item;

	/**
	 * refers to
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P67_refers_to}
	 * <p>
	 * Properties: P67.1 has type: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P67_refers_to">#P67_refers_to</a>
	 */
	public static final IRI P67_refers_to;

	/**
	 * foresees use of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P68_foresees_use_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P68_foresees_use_of">#P68_foresees_use_of</a>
	 */
	public static final IRI P68_foresees_use_of;

	/**
	 * is associated with
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P69_is_associated_with}
	 * <p>
	 * Properties: P69.1 has type: E55 Type
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P69_is_associated_with">#P69_is_associated_with</a>
	 */
	public static final IRI P69_is_associated_with;

	/**
	 * documents
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P70_documents}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P70_documents">#P70_documents</a>
	 */
	public static final IRI P70_documents;

	/**
	 * lists
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P71_lists}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P71_lists">#P71_lists</a>
	 */
	public static final IRI P71_lists;

	/**
	 * has language
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P72_has_language}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P72_has_language">#P72_has_language</a>
	 */
	public static final IRI P72_has_language;

	/**
	 * has translation
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P73_has_translation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P73_has_translation">#P73_has_translation</a>
	 */
	public static final IRI P73_has_translation;

	/**
	 * has current or former residence
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P74_has_current_or_former_residence}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P74_has_current_or_former_residence">#P74_has_current_or_former_residence</a>
	 */
	public static final IRI P74_has_current_or_former_residence;

	/**
	 * possesses
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P75_possesses}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P75_possesses">#P75_possesses</a>
	 */
	public static final IRI P75_possesses;

	/**
	 * has contact point
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P76_has_contact_point}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P76_has_contact_point">#P76_has_contact_point</a>
	 */
	public static final IRI P76_has_contact_point;

	/**
	 * is identified by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P78_is_identified_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P78_is_identified_by">#P78_is_identified_by</a>
	 */
	public static final IRI P78_is_identified_by;

	/**
	 * beginning is qualified by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P79_beginning_is_qualified_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P79_beginning_is_qualified_by">#P79_beginning_is_qualified_by</a>
	 */
	public static final IRI P79_beginning_is_qualified_by;

	/**
	 * took place at
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P7_took_place_at}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P7_took_place_at">#P7_took_place_at</a>
	 */
	public static final IRI P7_took_place_at;

	/**
	 * end is qualified by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P80_end_is_qualified_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P80_end_is_qualified_by">#P80_end_is_qualified_by</a>
	 */
	public static final IRI P80_end_is_qualified_by;

	/**
	 * ongoing throughout
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P81_ongoing_throughout}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P81_ongoing_throughout">#P81_ongoing_throughout</a>
	 */
	public static final IRI P81_ongoing_throughout;

	/**
	 * at some time within
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P82_at_some_time_within}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P82_at_some_time_within">#P82_at_some_time_within</a>
	 */
	public static final IRI P82_at_some_time_within;

	/**
	 * had at least duration
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P83_had_at_least_duration}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P83_had_at_least_duration">#P83_had_at_least_duration</a>
	 */
	public static final IRI P83_had_at_least_duration;

	/**
	 * had at most duration
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P84_had_at_most_duration}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P84_had_at_most_duration">#P84_had_at_most_duration</a>
	 */
	public static final IRI P84_had_at_most_duration;

	/**
	 * falls within
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P86_falls_within}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P86_falls_within">#P86_falls_within</a>
	 */
	public static final IRI P86_falls_within;

	/**
	 * is identified by
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P87_is_identified_by}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P87_is_identified_by">#P87_is_identified_by</a>
	 */
	public static final IRI P87_is_identified_by;

	/**
	 * consists of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P88_consists_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P88_consists_of">#P88_consists_of</a>
	 */
	public static final IRI P88_consists_of;

	/**
	 * falls within
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P89_falls_within}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P89_falls_within">#P89_falls_within</a>
	 */
	public static final IRI P89_falls_within;

	/**
	 * took place on or within
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P8_took_place_on_or_within}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P8_took_place_on_or_within">#P8_took_place_on_or_within</a>
	 */
	public static final IRI P8_took_place_on_or_within;

	/**
	 * has value
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P90_has_value}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P90_has_value">#P90_has_value</a>
	 */
	public static final IRI P90_has_value;

	/**
	 * has unit
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P91_has_unit}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P91_has_unit">#P91_has_unit</a>
	 */
	public static final IRI P91_has_unit;

	/**
	 * brought into existence
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P92_brought_into_existence}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P92_brought_into_existence">#P92_brought_into_existence</a>
	 */
	public static final IRI P92_brought_into_existence;

	/**
	 * took out of existence
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P93_took_out_of_existence}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P93_took_out_of_existence">#P93_took_out_of_existence</a>
	 */
	public static final IRI P93_took_out_of_existence;

	/**
	 * has created
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P94_has_created}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P94_has_created">#P94_has_created</a>
	 */
	public static final IRI P94_has_created;

	/**
	 * has formed
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P95_has_formed}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P95_has_formed">#P95_has_formed</a>
	 */
	public static final IRI P95_has_formed;

	/**
	 * by mother
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P96_by_mother}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P96_by_mother">#P96_by_mother</a>
	 */
	public static final IRI P96_by_mother;

	/**
	 * from father
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P97_from_father}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P97_from_father">#P97_from_father</a>
	 */
	public static final IRI P97_from_father;

	/**
	 * brought into life
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P98_brought_into_life}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P98_brought_into_life">#P98_brought_into_life</a>
	 */
	public static final IRI P98_brought_into_life;

	/**
	 * dissolved
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P99_dissolved}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P99_dissolved">#P99_dissolved</a>
	 */
	public static final IRI P99_dissolved;

	/**
	 * consists of
	 * <p>
	 * {@code http://purl.org/NET/cidoc-crm/core#P9_consists_of}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#P9_consists_of">#P9_consists_of</a>
	 */
	public static final IRI P9_consists_of;

	/**
	 * {@code http://purl.org/NET/cidoc-crm/core#PropertyNotation}
	 * @see <a href="http://purl.org/NET/cidoc-crm/core#PropertyNotation">#PropertyNotation</a>
	 */
	public static final IRI PropertyNotation;

	/**
	 * Static initializer
	 */
	static {
		ValueFactory vf = SimpleValueFactory.getInstance();

		NAMESPACE_IRI = vf.createIRI(NAMESPACE);

		/***********************
		 * IRI Constant creation
		 ***********************/
		E10_Transfer_of_Custody = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E10_Transfer_of_Custody");
		E11_Modification = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E11_Modification");
		E12_Production = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E12_Production");
		E13_Attribute_Assignment = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E13_Attribute_Assignment");
		E14_Condition_Assessment = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E14_Condition_Assessment");
		E15_Identifier_Assignment = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E15_Identifier_Assignment");
		E16_Measurement = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E16_Measurement");
		E17_Type_Assignment = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E17_Type_Assignment");
		E18_Physical_Thing = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E18_Physical_Thing");
		E19_Physical_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E19_Physical_Object");
		E1_CRM_Entity = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E1_CRM_Entity");
		E20_Biological_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E20_Biological_Object");
		E21_Person = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E21_Person");
		E22_Man_Made_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E22_Man-Made_Object");
		E24_Physical_Man_Made_Thing = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E24_Physical_Man-Made_Thing");
		E25_Man_Made_Feature = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E25_Man-Made_Feature");
		E26_Physical_Feature = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E26_Physical_Feature");
		E27_Site = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E27_Site");
		E28_Conceptual_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E28_Conceptual_Object");
		E29_Design_or_Procedure = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E29_Design_or_Procedure");
		E2_Temporal_Entity = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E2_Temporal_Entity");
		E30_Right = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E30_Right");
		E31_Document = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E31_Document");
		E32_Authority_Document = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E32_Authority_Document");
		E33_Linguistic_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E33_Linguistic_Object");
		E34_Inscription = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E34_Inscription");
		E35_Title = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E35_Title");
		E36_Visual_Item = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E36_Visual_Item");
		E37_Mark = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E37_Mark");
		E38_Image = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E38_Image");
		E39_Actor = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E39_Actor");
		E3_Condition_State = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E3_Condition_State");
		E40_Legal_Body = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E40_Legal_Body");
		E41_Appellation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E41_Appellation");
		E42_Identifier = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E42_Identifier");
		E44_Place_Appellation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E44_Place_Appellation");
		E45_Address = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E45_Address");
		E46_Section_Definition = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E46_Section_Definition");
		E47_Spatial_Coordinates = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E47_Spatial_Coordinates");
		E49_Time_Appellation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E49_Time_Appellation");
		E4_Period = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E4_Period");
		E50_Date = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E50_Date");
		E51_Contact_Point = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E51_Contact_Point");
		E52_Time_Span = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E52_Time-Span");
		E53_Place = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E53_Place");
		E54_Dimension = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E54_Dimension");
		E55_Type = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E55_Type");
		E56_Language = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E56_Language");
		E57_Material = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E57_Material");
		E58_Measurement_Unit = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E58_Measurement_Unit");
		E5_Event = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E5_Event");
		E63_Beginning_of_Existence = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E63_Beginning_of_Existence");
		E64_End_of_Existence = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E64_End_of_Existence");
		E65_Creation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E65_Creation");
		E66_Formation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E66_Formation");
		E67_Birth = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E67_Birth");
		E68_Dissolution = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E68_Dissolution");
		E69_Death = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E69_Death");
		E6_Destruction = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E6_Destruction");
		E70_Thing = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E70_Thing");
		E71_Man_Made_Thing = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E71_Man-Made_Thing");
		E72_Legal_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E72_Legal_Object");
		E73_Information_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E73_Information_Object");
		E74_Group = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E74_Group");
		E75_Conceptual_Object_Appellation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E75_Conceptual_Object_Appellation");
		E77_Persistent_Item = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E77_Persistent_Item");
		E78_Collection = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E78_Collection");
		E79_Part_Addition = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E79_Part_Addition");
		E7_Activity = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E7_Activity");
		E80_Part_Removal = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E80_Part_Removal");
		E81_Transformation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E81_Transformation");
		E82_Actor_Appellation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E82_Actor_Appellation");
		E83_Type_Creation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E83_Type_Creation");
		E84_Information_Carrier = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E84_Information_Carrier");
		E85_Joining = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E85_Joining");
		E86_Leaving = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E86_Leaving");
		E87_Curation_Activity = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E87_Curation_Activity");
		E89_Propositional_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E89_Propositional_Object");
		E8_Acquisition = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E8_Acquisition");
		E90_Symbolic_Object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E90_Symbolic_Object");
		E9_Move = vf.createIRI("http://purl.org/NET/cidoc-crm/core#E9_Move");
		EntityNotation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#EntityNotation");
		P100_was_death_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P100_was_death_of");
		P101_had_as_general_use = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P101_had_as_general_use");
		P102_has_title = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P102_has_title");
		P103_was_intended_for = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P103_was_intended_for");
		P104_is_subject_to = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P104_is_subject_to");
		P105_right_held_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P105_right_held_by");
		P106_is_composed_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P106_is_composed_of");
		P107_has_current_or_former_member = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P107_has_current_or_former_member");
		P108_has_produced = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P108_has_produced");
		P109_has_current_or_former_curator = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P109_has_current_or_former_curator");
		P10_falls_within = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P10_falls_within");
		P110_augmented = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P110_augmented");
		P111_added = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P111_added");
		P112_diminished = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P112_diminished");
		P113_removed = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P113_removed");
		P114_is_equal_in_time_to = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P114_is_equal_in_time_to");
		P115_finishes = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P115_finishes");
		P116_starts = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P116_starts");
		P117_occurs_during = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P117_occurs_during");
		P118_overlaps_in_time_with = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P118_overlaps_in_time_with");
		P119_meets_in_time_with = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P119_meets_in_time_with");
		P11_had_participant = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P11_had_participant");
		P120_occurs_before = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P120_occurs_before");
		P121_overlaps_with = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P121_overlaps_with");
		P122_borders_with = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P122_borders_with");
		P123_resulted_in = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P123_resulted_in");
		P124_transformed = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P124_transformed");
		P125_used_object_of_type = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P125_used_object_of_type");
		P126_employed = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P126_employed");
		P127_has_broader_term = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P127_has_broader_term");
		P128_carries = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P128_carries");
		P129_is_about = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P129_is_about");
		P12_occurred_in_the_presence_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P12_occurred_in_the_presence_of");
		P130_shows_features_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P130_shows_features_of");
		P131_is_identified_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P131_is_identified_by");
		P132_overlaps_with = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P132_overlaps_with");
		P133_is_separated_from = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P133_is_separated_from");
		P134_continued = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P134_continued");
		P135_created_type = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P135_created_type");
		P136_was_based_on = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P136_was_based_on");
		P137_exemplifies = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P137_exemplifies");
		P138_represents = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P138_represents");
		P139_has_alternative_form = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P139_has_alternative_form");
		P13_destroyed = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P13_destroyed");
		P140_assigned_attribute_to = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P140_assigned_attribute_to");
		P141_assigned = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P141_assigned");
		P142_used_constituent = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P142_used_constituent");
		P143_joined = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P143_joined");
		P144_joined_with = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P144_joined_with");
		P145_separated = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P145_separated");
		P146_separated_from = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P146_separated_from");
		P147_curated = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P147_curated");
		P148_has_component = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P148_has_component");
		P14_carried_out_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P14_carried_out_by");
		P15_was_influenced_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P15_was_influenced_by");
		P16_used_specific_object = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P16_used_specific_object");
		P17_was_motivated_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P17_was_motivated_by");
		P19_was_intended_use_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P19_was_intended_use_of");
		P1_is_identified_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P1_is_identified_by");
		P20_had_specific_purpose = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P20_had_specific_purpose");
		P21_had_general_purpose = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P21_had_general_purpose");
		P22_transferred_title_to = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P22_transferred_title_to");
		P23_transferred_title_from = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P23_transferred_title_from");
		P24_transferred_title_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P24_transferred_title_of");
		P25_moved = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P25_moved");
		P26_moved_to = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P26_moved_to");
		P27_moved_from = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P27_moved_from");
		P28_custody_surrendered_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P28_custody_surrendered_by");
		P29_custody_received_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P29_custody_received_by");
		P2_has_type = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P2_has_type");
		P30_transferred_custody_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P30_transferred_custody_of");
		P31_has_modified = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P31_has_modified");
		P32_used_general_technique = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P32_used_general_technique");
		P33_used_specific_technique = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P33_used_specific_technique");
		P34_concerned = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P34_concerned");
		P35_has_identified = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P35_has_identified");
		P37_assigned = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P37_assigned");
		P38_deassigned = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P38_deassigned");
		P39_measured = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P39_measured");
		P3_has_note = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P3_has_note");
		P40_observed_dimension = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P40_observed_dimension");
		P41_classified = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P41_classified");
		P42_assigned = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P42_assigned");
		P43_has_dimension = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P43_has_dimension");
		P44_has_condition = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P44_has_condition");
		P45_consists_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P45_consists_of");
		P46_is_composed_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P46_is_composed_of");
		P48_has_preferred_identifier = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P48_has_preferred_identifier");
		P49_has_former_or_current_keeper = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P49_has_former_or_current_keeper");
		P4_has_time_span = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P4_has_time-span");
		P50_has_current_keeper = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P50_has_current_keeper");
		P51_has_former_or_current_owner = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P51_has_former_or_current_owner");
		P52_has_current_owner = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P52_has_current_owner");
		P53_has_former_or_current_location = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P53_has_former_or_current_location");
		P54_has_current_permanent_location = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P54_has_current_permanent_location");
		P55_has_current_location = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P55_has_current_location");
		P56_bears_feature = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P56_bears_feature");
		P57_has_number_of_parts = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P57_has_number_of_parts");
		P58_has_section_definition = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P58_has_section_definition");
		P59_has_section = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P59_has_section");
		P5_consists_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P5_consists_of");
		P62_depicts = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P62_depicts");
		P65_shows_visual_item = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P65_shows_visual_item");
		P67_refers_to = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P67_refers_to");
		P68_foresees_use_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P68_foresees_use_of");
		P69_is_associated_with = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P69_is_associated_with");
		P70_documents = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P70_documents");
		P71_lists = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P71_lists");
		P72_has_language = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P72_has_language");
		P73_has_translation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P73_has_translation");
		P74_has_current_or_former_residence = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P74_has_current_or_former_residence");
		P75_possesses = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P75_possesses");
		P76_has_contact_point = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P76_has_contact_point");
		P78_is_identified_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P78_is_identified_by");
		P79_beginning_is_qualified_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P79_beginning_is_qualified_by");
		P7_took_place_at = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P7_took_place_at");
		P80_end_is_qualified_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P80_end_is_qualified_by");
		P81_ongoing_throughout = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P81_ongoing_throughout");
		P82_at_some_time_within = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P82_at_some_time_within");
		P83_had_at_least_duration = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P83_had_at_least_duration");
		P84_had_at_most_duration = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P84_had_at_most_duration");
		P86_falls_within = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P86_falls_within");
		P87_is_identified_by = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P87_is_identified_by");
		P88_consists_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P88_consists_of");
		P89_falls_within = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P89_falls_within");
		P8_took_place_on_or_within = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P8_took_place_on_or_within");
		P90_has_value = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P90_has_value");
		P91_has_unit = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P91_has_unit");
		P92_brought_into_existence = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P92_brought_into_existence");
		P93_took_out_of_existence = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P93_took_out_of_existence");
		P94_has_created = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P94_has_created");
		P95_has_formed = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P95_has_formed");
		P96_by_mother = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P96_by_mother");
		P97_from_father = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P97_from_father");
		P98_brought_into_life = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P98_brought_into_life");
		P99_dissolved = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P99_dissolved");
		P9_consists_of = vf.createIRI("http://purl.org/NET/cidoc-crm/core#P9_consists_of");
		PropertyNotation = vf.createIRI("http://purl.org/NET/cidoc-crm/core#PropertyNotation");
	}

	public CIDOC() {
		// To enable service discovery to succeed, even though this is a static class
	}
}
