PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT *
WHERE {
  {
    SELECT DISTINCT ?id { ?id a <http://dbpedia.org/ontology/Person> . } ORDER BY ?id  LIMIT 10 OFFSET 0
  }
  FILTER(BOUND(?id))
  OPTIONAL {
     ?id rdfs:label ?name . FILTER(langMatches(lang(?name), "en"))
  }
}
